services:
  db:
    image: mysql:8.0
    container_name: doingsdone-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: doingsdone
    ports:
      - "3308:3306"
    volumes:
      - doingsdone_mysql_data:/var/lib/mysql

volumes:
  doingsdone_mysql_data: